export const ErrorCodes = {
  COMMON: {
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
  },

  AUTH: {
    LOGIN_FAILED: "LOGIN_FAILED",
    EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
    EMAIL_VERIFICATION_FAILED: "EMAIL_VERIFICATION_FAILED",
    EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
    EMAIL_NOT_REGISTERED: "EMAIL_NOT_REGISTERED",
    TOKEN_REQUIRED: "TOKEN_REQUIRED",
    TOKEN_INVALID: "TOKEN_INVALID",
    WRONG_EMAIL_FORMAT: "WRONG_EMAIL_FORMAT",
    WRONG_PASSWORD_FORMAT: "WRONG_PASSWORD_FORMAT",
  },

  USER: {
    NOT_FOUND: "USER_NOT_FOUND",
    CURRENT_PASSWORD_NOT_MATCHED: "CURRENT_PASSWORD_NOT_MATCHED",
  },

  SURVEY: {
    QUESTIONS_NOT_FOUND: "QUESTIONS_NOT_FOUND",
  },

  INV_PROFILE: {
    INVALID_RISK_SCORE: "INVALID_RISK_SCORE",
    INVALID_INVESTMENT_PLAN: "INVALID_INVESTMENT_PLAN",
    INVESTMENT_PROFILE_NOT_FOUND: "INVESTMENT_PROFILE_NOT_FOUND",
  },

  PORTFOLIO: {
    NOT_FOUND: "PORTFOLIO_NOT_FOUND",
    INVALID_PORTIONS: "INVALID_PORTIONS",
    INVALID_DATA_FOR_ADDING_CATEGORY: "INVALID_DATA_FOR_ADDING_CATEGORY",
    INVALID_DATA_FOR_ADDING_ITEM: "INVALID_DATA_FOR_ADDING_ITEM",
  },
} as const;

// 타입 추출 (자동완성용)
type DeepExtract<T> = T extends object ? DeepExtract<T[keyof T]> : T;
export type ErrorCode = DeepExtract<typeof ErrorCodes>;
