export enum ErrorCode {
  EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  EMAIL_VERIFICATION_FAILED = "EMAIL_VERIFICATION_FAILED",
  EMAIL_NOT_REGISTERED = "EMAIL_NOT_REGISTERED",
  LOGIN_FAILED = "LOGIN_FAILED",
  WRONG_EMAIL_FORMAT = "WRONG_EMAIL_FORMAT",
  WRONG_PASSWORD_FORMAT = "WRONG_PASSWORD_FORMAT",
  USER_AUTHENTICATION_FAILED = "USER_AUTHENTICATION_FAILED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  CURRENT_PASSWORD_NOT_MATCHED = "CURRENT_PASSWORD_NOT_MATCHED",
}
