export enum ErrorCode {
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  EMAIL_VERIFICATION_FAILED = "EMAIL_VERIFICATION_FAILED",
  EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED",
  EMAIL_NOT_REGISTERED = "EMAIL_NOT_REGISTERED",

  LOGIN_FAILED = "LOGIN_FAILED",

  WRONG_EMAIL_FORMAT = "WRONG_EMAIL_FORMAT",
  WRONG_PASSWORD_FORMAT = "WRONG_PASSWORD_FORMAT",

  TOKEN_REQUIRED = "TOKEN_REQUIRED",
  TOKEN_INVALID = "TOKEN_INVALID",

  USER_NOT_FOUND = "USER_NOT_FOUND",
  CURRENT_PASSWORD_NOT_MATCHED = "CURRENT_PASSWORD_NOT_MATCHED",

  QUESTIONS_NOT_FOUND = "QUESTIONS_NOT_FOUND",
  INVALID_INVESTMENT_SCORE = "INVALID_INVESTMENT_SCORE",
  INVALID_INVESTMENT_PROFILE = "INVALID_INVESTMENT_PROFILE",
}
