export enum AuthErrorCode {
  AUTH_WRONG_EMAIL_FORMAT = "AUTH_WRONG_EMAIL_FORMAT",
  AUTH_WRONG_PASSWORD_FORMAT = "AUTH_WRONG_PASSWORD_FORMAT",
  AUTH_EMAIL_NOT_VERIFIED = "AUTH_EMAIL_NOT_VERIFIED",
  AUTH_EMAIL_ALREADY_REGISTERED = "AUTH_EMAIL_ALREADY_REGISTERED",
  AUTH_SIGN_IN_INVALID = "AUTH_SIGN_IN_INVALID",
  AUTH_EMAIL_VERIFICATION_FAILED = "AUTH_EMAIL_VERIFICATION_FAILED",
}
